- id: liccheck
  name: Run Python License Checker
  description: Check license compliance of python requirements
  entry: liccheck
  args: []
  language: python
  files: ^(.*requirements.*\.txt|setup\.cfg|setup\.py|pyproject\.toml|liccheck\.ini)$
  pass_filenames: false
