language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m pytest
deploy:
  provider: pypi
  user: Dev-Oss
  password:
    secure: gvva3bCMkmi95Ebahitij+DEDnpNBLl5Uyt7+OH+nJH+qHWfu4EZthcZbSJgjA4RFI4xHZS5DCTgmDkM6rhUyUwkNbQ6y62utpPEuzA7Wo2ymlgx/PIYeUXDWNWaDVvwSrbp35LNIyVJQcyuX4RboAwmKUDDdUKs4+nbep3yPTTSHnZXw4cqwHZvLUnlPy6Wgw9tCoOhB6eWYBXfzH9xIuOOuOVhR/DHgZEyB2rV+igBdAfv+BxwMBzG+iR5LsQtdfMs9OmC+L8AYu+WUYEPl/6pVwGtW5XmTv3rpD+yu0AeAp7OMPaPr9CD9/cJtiCP/TDnmQb+jeuyuzk58Ob5Ge6POQUzp60MGRfQCYKfPpV598NszARo+wKpMLMF+8xADWBenxVMULrTuw4T9oGOVNxBvfM8KWzqX8M6bUMswwD4gVhnuGKFNVCniNFSjgzhxBfb8tMeWp+QEIL0gwqLWP1QHVe/j9P5TSYpiVIaK3TAhRjH2xmFjKsmuSr1ztmrfd2jkXmF2AfaZRE/ODvIIpz52eWyq7Il+8RKI+rEf75y0WMjvZrxVDCrwpFd8I5Iaur2wieYCPXVfFXOTu8CZInbSPv3ofcps+b3E6/UOBT3GQ/YSIvZO8BDafFD7WROCDKA/56843QA5TXMg8s/lFMMUlN0746GCJ/6pR30rH8=
  on:
    tags: true
