language: python
python:
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m pytest
deploy:
  provider: pypi
  user: Dev-Oss
  password:
    secure: RUCiKhXXDIampjbP3P83kOx5m1Duiwp8dNb4qWj5IlM4lnw0CeJxVTZXpov7W3RogtKfjW/Y4t3tm6DJGU0oiifaWhdPoxHJ42q7Sx7zaMk2RvXIWzaRpspws1eItZqAuw8s2vmXs4NlgxHR79AUueEUntUAIm1Od1oxVNChMJnxo8aC5rdBdXV5V91Di7mgM2chLClua3tFHjKqT7wzz85xD3I17TicLhI6d2wV5X0IEk1kYCajjAaY1h43WYP9m3rZVibmeEW9ibFmkPK1ve5qZ9JNiAh2cMXrLnk3zeWhY1TCi6l8E/Df6Kki2Fh9TH1dqRuBWs/0USStbPrArQag7jTOEJn+S5FdcFLJPgqI7CSFxpM7r8ICvkb3Mp/+QolLxLWcwYzouMtziW1XQEZZR4gcm+tNa3Ffd/HLe3dWu3kRXdxY+ztX7Hak0J+gldhIDrxDw9tvtHn090nSTHbkGzfGfpL1mCDTFdaz1+mOuMKZHErG+6qPHc/z0nn5fVFaTsQIqrrgXs8NWIQKrJRCgsvau89EhZ7dEMPuoOk87vE/vQAeIqV5GyWsRBmMy3UhBhi4iBVmvKbgs3QMIl7KmZ/ozCwf7gKkty4ffKfv4zzzi5niX/zSjkRoaDKap+AsqEmXyWBH9RNaRMjO3OhTlsiYI0lc0Kcfx2fwT6Q=
  on:
    tags: true
