language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m pytest
deploy:
  provider: pypi
  user: Dev-Oss
  password:
    secure: jJ/gjsvYeUosXDjvyjc8Qu550TIWDhkjCOO9ZbhXgAxNES0Skss4xrJ4qPofEPI8qMeJY8mDxY79AV8edP+/D4kA7MnQ9yRQTNZXLNAV4xoH9gN/WRGCZkxcUwBtJrSrPu/sKbmWqjIc3UK9j1leMgRrEOSD3BqdSsrg+g+eoQf72AY37svB1AkHdF9E3QWVoB6LUjaksrEHNt99HGYPdiDmCCmagY3MpX0IldaYfegCP096mYpqeM/HQgfcTlBhuu6uxO6AIv60oDQmWADTQPvUn5fWO0KKs/yEQuLvfd9CR4LTooTrYrBk8GAzLo0seMxIquzsIEmia/pOded32nGNToMwHV4Rg0W/RF5hTtD/pVRmWzlzZGiM7Domgy/MovPTNDWRz2DDaeLlJm5p1dYXTzDrU4Qp20R3OBbr/2l3jaiH+tUTwM4KxKKm7ZZB0xAzdtuQw1aIG54MuCdKVrf0RFEk8+eCWNC5r9bUQV1P2XAfvIwJ+Obwt/egOnPr+hzlbZMIOQhFCkprPVgPYbXWx/GOyNLyO+D80YDQCgtfflxGAo/5nMmh0cdHNhcGyxFxl+e8yD36WUdQdDofU2DTY0YIlm1LM3h0QzQjE76BEe1m7lkxSa+TbnmpAGXulPlZtj10DwdKJQd5tqk+6fRW4RdYMImiq2AHSk1aqkc=
  on:
    tags: true
